blank_issues_enabled: true
contact_links:
  - name: Security report
    url: https://github.com/lokiloko7777-tech/Free-Live-Personal-TV/security/policy
    about: Za bezbednosne prijave koristi Security Policy.